/*
Highly divisible triangular number
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:
1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

#include<iostream>
#include<cmath>

using namespace std;

long long count_of_dividers(long long n){
    long long sum=0;
    for (long long i = 1; i <= sqrt(n); ++i)
    {
        if (n%i==0) sum=sum+2;
    }
    return sum;
}

long long sum(long long n){
    return n*(n+1)/2;
}

int main(){
    int n;
    cin>>n;
    int i=1;
    while(count_of_dividers(sum(i))<n){
        i++;
    }
    cout<<sum(i);
}
